### ISSUE TITLE
Support VCS dependencies

### ISSUE THREAD

**Issue by yu-re-ka** [nix-community/composer-local-repo-plugin#5]
## Steps required to reproduce the problem

1. A repository with vcs dependency (like https://github.com/inex/IXP-Manager, https://github.com/snipe/snipe-it)
2. Build the package with buildComposerProject
3. See it attempt to clone the dependency repository in the main derivation, and fail

## Expected Result

- The vcs dependencies should be downloaded as part of the composerRepository fixed-output derivation

## Actual Result

- The vcs dependencies are not to be found in the composerRepository out path

**Comment by drupol** [comment]
Hi !

What is the error that you get when trying to do so ?

**Comment by yu-re-ka** [comment]
package.nix:

```
{ php
, fetchFromGitHub
}:

php.buildComposerProject rec {
  pname = "snipe-it";
  version = "6.2.2";

  src = fetchFromGitHub {
    owner = "snipe";
    repo = "snipe-it";
    rev = "v${version}";
    hash = "sha256-EU+teGxo7YZkD7kNXk9jRyARpzWz5OMRmaWqQ6eMKYY=";
  };

  vendorHash = "sha256-JcBcrETbjGJFlG1dH/XXqmb9MlKr0ICdnEx7/61Z5io=";
}
```

error log:
```
building
Executing composerInstallBuildHook
Local repository manifest "packages.json" has been successfully created in /nix/store/svm6bqj03m8gpx5cf62ymfch0xby6pwf-snipe-it-6.2.2-composer-repository
Loading composer repositories with package information
Cannot create cache directory /homeless-shelter/.cache/composer/repo/file----build-source-packages.json/, or directory is not writable. Proceeding without cache. See a>
Failed to clone the git@github.com:grokability/laravel-scim-server.git repository, try running in interactive mode so that you can enter your GitHub credentials

In Filesystem.php line 255:
                                                                               
  /homeless-shelter/.cache/composer/vcs does not exist and could not be creat  
  ed.                                                                          
                                                                               

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-f>
```

**Comment by drupol** [comment]
Shouldn't be that complicated to fix I guess. I will have a look tonight.

In the meantime and if you're already looking for a solution, check [this](https://github.com/NixOS/nixpkgs/blob/0188c8758f8a6f00ef4a3ffc60111b19828e1ee9/pkgs/build-support/php/hooks/composer-install-hook.sh#L73) and try to add the env var: `COMPOSER_CACHE_DIR=/dev/null` and see if it fixes the issue.

**Comment by yu-re-ka** [comment]
setting `COMPOSER_CACHE_DIR=/dev/null` results in:

```
Failed to clone the git@github.com:grokability/laravel-scim-server.git repository, try running in interactive mode so that you can enter your GitHub credentials

In GitDriver.php line 52:
                                                                               
  GitDriver requires a usable cache directory, and it looks like you set it t  
  o be disabled                                                                
                                                                               

```

~~It can't work without changes to composer-local-repo-plugin, because the dependency is not available to the main derivation.~~ Setting the cache directory to /tmp (which is writable), results in this:

```
Aborting git mirror sync of git@github.com:grokability/laravel-scim-server.git as network is disabled
Failed to clone the git@github.com:grokability/laravel-scim-server.git repository, try running in interactive mode so that you can enter your GitHub credentials

In GitDriver.php line 73:
                                                                               
  Failed to clone git@github.com:grokability/laravel-scim-server.git to read   
  package information from it                                                  
                                                                               
```

**Comment by drupol** [comment]
Oh. That's problematic.

I don't see yet how to fix that sadly :(

**Comment by yu-re-ka** [comment]
Actually, the dependency is part of the cache: `${composerRepository}/arietimmerman/laravel-scim-server/dev-master/`

I guess just removing the vcs dependency entry might work

**Comment by drupol** [comment]
I don't know yet... I'm at work, I can't really check deeper right now :(

**Comment by drupol** [comment]
@yu-re-ka I guess this issue can be closed now?

**Comment by yu-re-ka** [comment]
Yes, this is fixed

22 Oct 2023 18:08:33 Pol Dellaiera ***@***.***>:

**Comment by drupol** [comment]
How about closing the issue ? 🙄

**Comment by yu-re-ka** [comment]
I am not logged in to the github ui on my phone, thus I could only respond to the email
